(function(){var h={},mt={},c={id:"6bcd52f51e9b3dce32bec4a3997715ac",dm:["csdn.net","dingyue.programmer.com.cn","gitbook.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'',ctrk:true,align:0,nv:1,vdur:1800000,age:31536000000,rec:1,rp:[[119608, 2]],trust:0,vcard:0,qiao:0,lxb:0,kbtrk:0,pt:0,spa:0,aet:'a,input,button',hca:'0D7119607F77DEA9',conv:0,med:0,cvcc:'',cvcf:[],apps:''};var s=void 0,u=!0,v=null,w=!1;mt.cookie={};mt.cookie.set=function(a,b,g){var d;g.R&&(d=new Date,d.setTime(d.getTime()+g.R));document.cookie=a+"="+b+(g.domain?"; domain="+g.domain:"")+(g.path?"; path="+g.path:"")+(d?"; expires="+d.toGMTString():"")+(g.Hc?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:v};
mt.cookie.ec=function(a,b){try{var g="Hm_ck_"+ +new Date;mt.cookie.set(g,"is-cookie-enabled",{domain:a,path:b,R:s});var d="is-cookie-enabled"===mt.cookie.get(g)?"1":"0";mt.cookie.set(g,"",{domain:a,path:b,R:-1});return d}catch(e){return"0"}};mt.lang={};mt.lang.e=function(a,b){return"[object "+b+"]"==={}.toString.call(a)};mt.lang.Da=function(a){return mt.lang.e(a,"Number")&&isFinite(a)};mt.lang.L=function(a){return mt.lang.e(a,"String")};mt.lang.isArray=function(a){return mt.lang.e(a,"Array")};
mt.lang.g=function(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a};mt.lang.trim=function(a){return a.replace(/^\s+|\s+$/g,"")};mt.lang.K=function(a,b){var g=w;if(a==v||!mt.lang.e(a,"Array")||b===s)return g;if(Array.prototype.indexOf)g=-1!==a.indexOf(b);else for(var d=0;d<a.length;d++)if(a[d]===b){g=u;break}return g};mt.url={};mt.url.m=function(a,b){var g=a.match(RegExp("(^|&|\\?|#)("+b+")=([^&#]*)(&|$|#)",""));return g?g[3]:v};
mt.url.Ec=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:v};mt.url.Ib=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):v};mt.url.V=function(a){return(a=mt.url.Ib(a))?a.replace(/:\d+$/,""):a};mt.url.ya=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):v};
(function(){var a=mt.lang,b=mt.url;mt.f={};mt.f.va=function(a){return document.getElementById(a)};mt.f.wa=function(a){if(!a)return v;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var d=a.split(">"),e=document.body,b=d.length-1;0<=b;b--)if(-1<d[b].indexOf("#")){var f=d[b].split("#")[1];(e=document.getElementById(f))||(e=document.getElementById(decodeURIComponent(f)));d=d.splice(b+1,d.length-(b+1));break}for(a=
0;e&&a<d.length;){var l=String(d[a]).toLowerCase();if(!("html"===l||"body"===l)){var b=0,q=d[a].match(/\[(\d+)\]/i),f=[];if(q)b=q[1]-1,l=l.split("[")[0];else if(1!==e.childNodes.length){for(var r=0,t=0,n=e.childNodes.length;t<n;t++){var x=e.childNodes[t];1===x.nodeType&&x.nodeName.toLowerCase()===l&&r++;if(1<r)return v}if(1!==r)return v}for(r=0;r<e.childNodes.length;r++)1===e.childNodes[r].nodeType&&e.childNodes[r].nodeName.toLowerCase()===l&&f.push(e.childNodes[r]);if(!f[b])return v;e=f[b]}a++}return e}catch(k){return v}};
mt.f.ya=function(a,d){var e=[],b=[];if(!a)return b;for(;a.parentNode!=v;){for(var f=0,l=0,q=a.parentNode.childNodes.length,r=0;r<q;r++){var t=a.parentNode.childNodes[r];if(t.nodeName===a.nodeName&&(f++,t===a&&(l=f),0<l&&1<f))break}if((q=""!==a.id)&&d){e.unshift("#"+encodeURIComponent(a.id));break}else q&&(q="#"+encodeURIComponent(a.id),q=0<e.length?q+">"+e.join(">"):q,b.push(q)),e.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+l+"]":""));a=a.parentNode}b.push(e.join(">"));return b};
mt.f.ea=function(a){return(a=mt.f.ya(a,u))&&a.length?String(a[0]):""};mt.f.Nb=function(a){return mt.f.ya(a,w)};mt.f.Cb=function(a){var d;for(d="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==d)return a;return v};mt.f.Fb=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.f.Lb=function(a){var d={top:0,left:0};if(!a)return d;var e=mt.f.Fb(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(d=a.getBoundingClientRect());return{top:d.top+(window.pageYOffset||e.scrollTop)-
(e.clientTop||0),left:d.left+(window.pageXOffset||e.scrollLeft)-(e.clientLeft||0)}};mt.f.getAttribute=function(a,d){var e=a.getAttribute&&a.getAttribute(d)||v;if(!e&&a.attributes&&a.attributes.length)for(var b=a.attributes,f=b.length,l=0;l<f;l++)b[l].nodeName===d&&(e=b[l].nodeValue);return e};mt.f.U=function(a){var d="document";a.tagName!==s&&(d=a.tagName);return d.toLowerCase()};mt.f.Qb=function(b){var d="";b.textContent?d=a.trim(b.textContent):b.innerText&&(d=a.trim(b.innerText));d&&(d=d.replace(/\s+/g,
" ").substring(0,255));return d};mt.f.T=function(g,d){var e;a.L(g)&&0===String(g).indexOf("!HMCQ!")?(e=String(g),e=b.m(document.location.href,e.substring(6,e.length))):a.L(g)||(e=mt.f.U(g),"input"===e&&d&&("button"===g.type||"submit"===g.type)?e=a.trim(g.value)||"":"input"===e&&!d&&"password"!==g.type?e=a.trim(g.value)||"":"img"===e?(e=mt.f.getAttribute,e=e(g,"alt")||e(g,"title")||e(g,"src")):e="body"===e||"html"===e?["(hm-default-content-for-",e,")"].join(""):mt.f.Qb(g));return String(e||"").substring(0,
255)};(function(){(mt.f.Ia=function(){function a(){if(!a.ga){a.ga=u;for(var d=0,b=m.length;d<b;d++)m[d]()}}function d(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(d,1);return}a()}var b=w,m=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,w);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!b)if(b=u,"complete"===document.readyState)a.ga=u;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var l=w;try{l=window.frameElement==v}catch(q){}document.documentElement.doScroll&&l&&d()}})();return function(d){a.ga?d():m.push(d)}}()).ga=w})();return mt.f})();mt.event={};
mt.event.d=function(a,b,g){a.attachEvent?a.attachEvent("on"+b,function(d){g.call(a,d)}):a.addEventListener&&a.addEventListener(b,g,w)};mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};
(function(){var a=mt.event;mt.h={};mt.h.Ca=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.h.Jb=function(){if(document.documentMode)return document.documentMode;var a=/msie (\d+\.\d+)/i.exec(navigator.userAgent);return a?+a[1]||0:0};mt.h.bc=function(){try{return!!navigator.userAgent.match(/safari/i)&&!navigator.userAgent.match(/chrome/i)&&"undefined"!==typeof document.body.style.webkitFilter&&!window.chrome}catch(a){return w}};mt.h.cookieEnabled=navigator.cookieEnabled;mt.h.javaEnabled=navigator.javaEnabled();
mt.h.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.h.nc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.h.colorDepth=window.screen.colorDepth||0;mt.h.W=function(){var a;a=a||document;return parseInt(window.pageYOffset||a.documentElement.scrollTop||a.body&&a.body.scrollTop||0,10)};mt.h.J=function(){var a=document;return parseInt(window.innerHeight||a.documentElement.clientHeight||a.body&&a.body.clientHeight||0,10)};mt.h.orientation=
0;(function(){function b(){var a=0;window.orientation!==s&&(a=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==s)&&(a=screen.orientation.angle);mt.h.orientation=a}b();a.d(window,"orientationchange",b)})();return mt.h})();mt.o={};mt.o.parse=function(a){return(new Function("return ("+a+")"))()};
mt.o.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=g[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function b(a){return 10>a?"0"+a:a}var g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===v)return"null";if(d instanceof Array){var e=["["],g=d.length,f,l,q;for(l=0;l<g;l++)switch(q=d[l],typeof q){case "undefined":case "function":case "unknown":break;default:f&&e.push(","),e.push(mt.o.stringify(q)),f=1}e.push("]");return e.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+b(d.getMonth()+1)+"-"+b(d.getDate())+"T"+b(d.getHours())+":"+b(d.getMinutes())+":"+b(d.getSeconds())+'"';f=["{"];l=mt.o.stringify;for(g in d)if(Object.prototype.hasOwnProperty.call(d,g))switch(q=
d[g],typeof q){case "undefined":case "unknown":case "function":break;default:e&&f.push(","),e=1,f.push(l(g)+":"+l(q))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.pa=function(){if(!mt.localStorage.l)try{mt.localStorage.l=document.createElement("input"),mt.localStorage.l.type="hidden",mt.localStorage.l.style.display="none",mt.localStorage.l.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.l)}catch(a){return w}return u};
mt.localStorage.set=function(a,b,g){var d=new Date;d.setTime(d.getTime()+g||31536E6);try{window.localStorage?(b=d.getTime()+"|"+b,window.localStorage.setItem(a,b)):mt.localStorage.pa()&&(mt.localStorage.l.expires=d.toUTCString(),mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.setAttribute(a,b),mt.localStorage.l.save(document.location.hostname))}catch(e){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var b=a.indexOf("|"),g=a.substring(0,b)-0;if(g&&g>(new Date).getTime())return a.substring(b+1)}}else if(mt.localStorage.pa())try{return mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.getAttribute(a)}catch(d){}return v};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.pa())try{mt.localStorage.l.load(document.location.hostname),mt.localStorage.l.removeAttribute(a),mt.localStorage.l.save(document.location.hostname)}catch(b){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,b){try{window.sessionStorage&&window.sessionStorage.setItem(a,b)}catch(g){}};
mt.sessionStorage.get=function(a){try{return window.sessionStorage?window.sessionStorage.getItem(a):v}catch(b){return v}};mt.sessionStorage.remove=function(a){try{window.sessionStorage&&window.sessionStorage.removeItem(a)}catch(b){}};mt.bb={};mt.bb.log=function(a,b){var g=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=g;g.onload=function(){g.onload=v;g=window[d]=v;b&&b(a)};g.src=a};mt.Ja={};
mt.Ja.Rb=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var b=navigator.plugins["Shockwave Flash"];b&&b.description&&(a=b.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=b.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(g){}return a};
mt.Ja.Dc=function(a,b,g,d,e){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+g+'" height="'+d+'"><param name="movie" value="'+b+'" /><param name="flashvars" value="'+(e||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+g+'" height="'+d+'" src="'+b+'" flashvars="'+(e||"")+'" allowscriptaccess="always" /></object>'};
(function(){function a(){for(var a=w,g=document.getElementsByTagName("script"),d=g.length,d=100<d?100:d,e=0;e<d;e++){var m=g[e].src;if(m&&0===m.indexOf("https://hm.baidu.com/h")){a=u;break}}return a}return h.Ab=a})();var A=h.Ab;
h.s={Fc:"http://tongji.baidu.com/hm-web/welcome/ico",Ha:"hm.baidu.com/hm.gif",mb:/^(tongji|hmcdn).baidu.com$/,eb:"tongji.baidu.com",Wb:"hmmd",Xb:"hmpl",zc:"utm_medium",Vb:"hmkw",Bc:"utm_term",Tb:"hmci",yc:"utm_content",Yb:"hmsr",Ac:"utm_source",Ub:"hmcu",xc:"utm_campaign",M:0,H:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ia:A()||"https:"===document.location.protocol?"https:":"http:",Gc:0,tb:6E5,fc:6E5,oc:5E3,ub:5,P:1024,rb:1,N:2147483647,cb:"hca kb cc cf ci ck cl cm cp cu cw ds vl ep et fl ja ln lo lt rnd si su v cv lv api sn p ct u tt".split(" "),
X:u,Oa:["a","input","button"],La:{id:"data-hm-id",ba:"data-hm-class",aa:"data-hm-xpath",content:"data-hm-content",ma:"data-hm-tag",link:"data-hm-link"},Na:"data-hm-enabled",Ma:"data-hm-disabled",jc:"https://hmcdn.baidu.com/static/tongji/plugins/",Ya:["UrlChangeTracker"]};(function(){var a={D:{},d:function(a,g){this.D[a]=this.D[a]||[];this.D[a].push(g)},I:function(a,g){this.D[a]=this.D[a]||[];for(var d=this.D[a].length,e=0;e<d;e++)this.D[a][e](g)}};return h.w=a})();
(function(){function a(a,d){var e=document.createElement("script");e.charset="utf-8";b.e(d,"Function")&&(e.readyState?e.onreadystatechange=function(){if("loaded"===e.readyState||"complete"===e.readyState)e.onreadystatechange=v,d()}:e.onload=function(){d()});e.src=a;var m=document.getElementsByTagName("script")[0];m.parentNode.insertBefore(e,m)}var b=mt.lang;return h.load=a})();
(function(){function a(){var a="";if(h.c.b.nv){a=encodeURIComponent(document.referrer);try{window.sessionStorage?g.set("Hm_from_"+c.id,a):b.set("Hm_from_"+c.id,a,864E5)}catch(e){}}else try{a=(window.sessionStorage?g.get("Hm_from_"+c.id):b.get("Hm_from_"+c.id))||""}catch(m){}return a}var b=mt.localStorage,g=mt.sessionStorage;return h.Bb=a})();
(function(){var a=mt.cookie,b=mt.localStorage,g=mt.sessionStorage,d={getData:function(d){try{return a.get(d)||g.get(d)||b.get(d)}catch(m){}},setData:function(e,m,f){try{a.set(e,m,{domain:d.S(),path:d.da(),R:f}),f?b.set(e,m,f):g.set(e,m)}catch(l){}},mc:function(e){try{a.set(e,"",{domain:d.S(),path:d.da(),R:-1}),g.remove(e),b.remove(e)}catch(m){}},Y:function(a,d){a="."+a.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var b=a.indexOf(d);return-1<b&&b+d.length===a.length},ha:function(a,d){a=a.replace(/^https?:\/\//,
"");return 0===a.indexOf(d)},S:function(){for(var a=document.location.hostname,b=0,f=c.dm.length;b<f;b++)if(d.Y(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},da:function(){for(var a=0,b=c.dm.length;a<b;a++){var f=c.dm[a];if(-1<f.indexOf("/")&&d.ha(document.location.href,f))return f.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.sa=d})();
(function(){var a=mt.lang,b=mt.o,g=h.sa,d={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},e={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},m=["session","user"],f="Hm_up_"+c.id,l={init:function(){l.ac()},ac:function(){try{var e=b.parse(decodeURIComponent(g.getData(f)));a.e(e,"Object")&&(d.user=e)}catch(r){}},A:function(a){var b={};d[a]!==s&&(b=d[a]);a=this.za();for(var e in b)b.hasOwnProperty(e)&&(a[e]=b[e]);return a},za:function(){for(var a={},b,e=m.length-
1;0<=e;e--){b=d[m[e]];for(var n in b)b.hasOwnProperty(n)&&(a[n]=b[n])}return a},setProperty:function(e,r,f){var n=d[e];if(a.e(n,"Object")&&a.e(r,"Object")){for(var g in r)if(r.hasOwnProperty(g)){var k=a.g(String(g));if(f||!/^_/.test(k)&&!/_$/.test(k)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(k)){var p=r[g];if(p==v)delete n[k];else{if(a.e(p,"Object")||a.e(p,"Array"))p=b.stringify(p);p=a.g(String(p));l.dc(e,k,p)&&(n[k]={value:p,scope:l.Sa(e)})}}}"user"===e&&l.Fa()}},r:function(b){b!==s&&("userId"===
b&&a.e(d.user,"Object")?(delete d.user.uid_,l.Fa()):"user"===b&&a.e(d.user,"Object")?(b=d.user.uid_,d.user=b===s?{}:{uid_:b},l.Fa()):d[b]!==s&&(d[b]={}))},Fa:function(){try{g.setData(f,encodeURIComponent(b.stringify(d.user)),c.age)}catch(a){}},dc:function(a,b,e){var n=u,f=d[a];if(256<encodeURIComponent(String(b)).length||256<encodeURIComponent(String(e)).length)n=w;else{var k=f[b];f[b]={value:e,scope:l.Sa(a)};a=l.O(l.A(a));2048<encodeURIComponent(a).length&&(k!==s?f[b]=k:delete f[b],n=w)}return n},
O:function(a){var d=[],b,e;for(e in a)a.hasOwnProperty(e)&&(b=[e,a[e].value],(1===a[e].scope||2===a[e].scope)&&b.push(a[e].scope),d.push(b.join("*")));return d.join("!")},Sa:function(a){a=e[a];return a!==s?a:e.others}};return h.Q=l})();
(function(){var a=mt.f,b=mt.lang,g=mt.o,d=h.w,e=h.Q,m=e.O;if(b.isArray(c.cptrk)&&0<c.cptrk.length){var f={Xa:{},na:{},init:function(){for(var a,d=0;d<c.cptrk.length;d++)try{if(a=g.parse(decodeURIComponent(String(c.cptrk[d]))),a.a!==s&&b.e(a.a,"Object")){var e=a.a,m;for(m in e)e.hasOwnProperty(m)&&(f.na[m]=String(e[m]))}}catch(n){}},Wa:function(){var d,b,e;for(e in f.na)if(f.na.hasOwnProperty(e)&&f.Xa[e]===s&&(d=f.na[e],d=a.wa(d)))b=b===s?{}:b,b[e]=a.T(d,w),f.Xa[e]=u;return b},Aa:function(){var a=
f.Wa();a&&f.rc(a)},$b:function(){"MutationObserver"in window?(new MutationObserver(f.Aa)).observe(document.body,{childList:u,subtree:u}):window.setInterval(f.Aa,15E3)},rc:function(a){if(b.e(a,"Object")){e.setProperty("pageview",a);a=h.c.b.p;var d=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=m(e.A("pageview"));h.c.i();h.c.b.p=a;h.c.b.ep=d;e.r("pageview")}}};f.init();d.d("pv-b",function(){var a=f.Wa();a&&e.setProperty("pageview",a)});f.$b();a.Ia(f.Aa)}})();
(function(){var a=mt.lang,b=mt.f,g={ca:function(a,e){return function(m){var f=m.target||m.srcElement;if(f){var l=f.getAttribute(a.oa);m=m.clientX+":"+m.clientY;if(l&&l===m)f.removeAttribute(a.oa);else if(e&&0<e.length&&(f=b.Nb(f))&&f.length)if(l=f.length,m=f[f.length-1],1E4>l*m.split(">").length)for(m=0;m<l;m++)g.ab(a,f[m]);else g.ab(a,m)}}},ab:function(d,b){for(var g={},f=String(b).split(">").length,l=0;l<f;l++)g[b]="",b=b.substring(0,b.lastIndexOf(">"));d&&(a.e(d,"Object")&&d.Pa)&&d.Pa(g)},lc:function(a,
b){return function(g){(g.target||g.srcElement).setAttribute(a.oa,g.clientX+":"+g.clientY);a&&a.z&&(b?a.z(b):a.z("#"+encodeURIComponent(this.id),g.type))}}};return h.ua=g})();
(function(){var a=mt.f,b=mt.o,g=mt.event,d=mt.lang,e=h.s,m=h.ua,f=h.Q,l=f.O,q={oa:"HM_ce",gb:function(){if(c.cetrk&&c.cetrk.length){g.d(document,"click",m.ca(q,c.cetrk));for(var d=0,e=c.cetrk.length;d<e;d++){var n;try{n=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(f){n={}}var k=n.p||"";-1===k.indexOf(">")&&(0===k.indexOf("#")&&(k=k.substring(1)),(k=a.va(k))&&g.d(k,"click",m.lc(q,n)))}}},Pa:function(a){if(c.cetrk&&c.cetrk.length)for(var d=0,e=c.cetrk.length;d<e;d++){var f;try{f=b.parse(decodeURIComponent(String(c.cetrk[d])))}catch(k){f=
{}}var p=q.Gb(f.p,a);p&&q.z(f,p)}},Gb:function(a,d){a=String(a);if(0<a.indexOf("*")){var b=RegExp("^"+a.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),e;for(e in d)if(d.hasOwnProperty(e)&&b.test(e))return e;return v}return d.hasOwnProperty(a)?a:v},z:function(b,e){h.c.b.et=7;var g=b&&b.k||"",g=d.g(g),m={};if(b&&b.a&&d.e(b.a,"Object")){var k=b.a,p;for(p in k)if(k.hasOwnProperty(p)){var y=q.Ob(k[p]||"",e),y=y?a.T(y,w):"";m[p]=y}}m=q.Db(m,e||b&&b.p);m._iden=g;f.setProperty("customEvent",
m);h.c.b.ep="";h.c.b.p=l(f.A("customEvent"));h.c.i();h.c.b.p="";f.r("customEvent")},Db:function(b,d){var f=a.wa(d),g=e.La;f&&(c.aet&&c.aet.length?(b.ei_=a.getAttribute(f,g.id)||a.getAttribute(f,"id")||"",b.ec_=a.getAttribute(f,g.ba)||a.getAttribute(f,"class")||"",b.ex_=a.getAttribute(f,g.aa)||a.ea(f),b.en_=a.getAttribute(f,g.content)||a.T(f,u),b.et_=a.getAttribute(f,g.ma)||a.U(f),b.el_=a.getAttribute(f,g.link)||a.getAttribute(f,"href")||""):(b.ex_=a.getAttribute(f,g.aa)||a.ea(f),b.en_=a.getAttribute(f,
g.content)||a.T(f,u)));return b},Ob:function(b,d){b=String(b);d=String(d);if(0<b.indexOf("*")){var e=/.*\[(\d+)\]$/.exec(d);b=b.replace("*",e?e[1]:"1")}return a.wa(b)}};h.w.d("pv-b",q.gb);return q})();
(function(){var a=mt.f,b=mt.lang,g=mt.event,d=mt.h,e=h.s,m=h.w,f=[],l={fb:function(){c.ctrk&&(g.d(document,"mouseup",l.qb()),g.d(window,"unload",function(){l.ka()}),setInterval(function(){l.ka()},e.tb))},qb:function(){return function(a){a=l.Eb(a);if(""!==a){var b=(e.ia+"//"+e.Ha+"?"+h.c.$a().replace(/ep=[^&]*/,"ep="+encodeURIComponent(a))).length;b+(e.N+"").length>e.P||(b+encodeURIComponent(f.join("!")+(f.length?"!":"")).length+(e.N+"").length>e.P&&l.ka(),f.push(a),(f.length>=e.ub||/\*a\*/.test(a))&&
l.ka())}}},Eb:function(f){var g=f.target||f.srcElement;if(0===e.rb){var n=(g.tagName||"").toLowerCase();if("embed"==n||"object"==n)return""}var m;d.Ca?(m=Math.max(document.documentElement.scrollTop,document.body.scrollTop),n=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),n=f.clientX+n,m=f.clientY+m):(n=f.pageX,m=f.pageY);f=l.Kb(f,g,n,m);var k=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:n-=k/2;break;case 2:n-=k}k=
[];k.push(n);k.push(m);k.push(f.gc);k.push(f.hc);k.push(f.kc);k.push(b.g(f.ic));k.push(f.Cc);k.push(f.Sb);(g="a"===(g.tagName||"").toLowerCase()?g:a.Cb(g))?(k.push("a"),k.push(b.g(encodeURIComponent(g.href)))):k.push("b");return k.join("*")},Kb:function(e,f,g,l){e=a.ea(f);var k=0,p=0,y=0,z=0;if(f&&(k=f.offsetWidth||f.clientWidth,p=f.offsetHeight||f.clientHeight,z=a.Lb(f),y=z.left,z=z.top,b.e(f.getBBox,"Function")&&(p=f.getBBox(),k=p.width,p=p.height),"html"===(f.tagName||"").toLowerCase()))k=Math.max(k,
f.clientWidth),p=Math.max(p,f.clientHeight);return{gc:Math.round(100*((g-y)/k)),hc:Math.round(100*((l-z)/p)),kc:d.orientation,ic:e,Cc:k,Sb:p}},ka:function(){0!==f.length&&(h.c.b.et=2,h.c.b.ep=f.join("!"),h.c.i(),f=[])}},q={jb:function(){c.ctrk&&setInterval(q.pc,e.oc)},pc:function(){var a=d.W()+d.J();0<a-h.c.b.vl&&(h.c.b.vl=a)}};m.d("pv-b",l.fb);m.d("pv-b",q.jb);return l})();
(function(){var a=mt.lang,b=mt.f,g=mt.event,d=mt.h,e=h.s,m=h.w,f=h.Q,l=f.O,q=+new Date,r=[],t={ca:function(){return function(d){if(h.c&&h.c.X&&c.aet&&c.aet.length){var f=d.target||d.srcElement;if(f){var g=h.c.Oa,p=b.getAttribute(f,e.Na)!=v?u:w;if(b.getAttribute(f,e.Ma)==v)if(p)t.qa(t.xa(f,d));else{var y=b.U(f);if(a.K(g,"*")||a.K(g,y))t.qa(t.xa(f,d));else for(;f.parentNode!=v;){var p=f.parentNode,y=b.U(p),z="a"===y&&a.K(g,"a")?u:w,y="button"===y&&a.K(g,"button")?u:w,B=b.getAttribute(p,e.Na)!=v?u:w;
if(b.getAttribute(p,e.Ma)==v&&(z||y||B)){t.qa(t.xa(p,d));break}f=f.parentNode}}}}}},xa:function(f,g){var k={},p=e.La;k.id=b.getAttribute(f,p.id)||b.getAttribute(f,"id")||"";k.ba=b.getAttribute(f,p.ba)||b.getAttribute(f,"class")||"";k.aa=b.getAttribute(f,p.aa)||b.ea(f);k.content=b.getAttribute(f,p.content)||b.T(f,u);k.ma=b.getAttribute(f,p.ma)||b.U(f);k.link=b.getAttribute(f,p.link)||b.getAttribute(f,"href")||"";k.type=g.type||"click";p=a.Da(f.offsetTop)?f.offsetTop:0;"click"===g.type?p=d.Ca?g.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):g.pageY:"touchend"===g.type&&(g.Ea&&a.e(g.Ea.changedTouches,"Array")&&g.Ea.changedTouches.length)&&(p=g.Ea.changedTouches[0].pageY);k.wc=p;return k},qa:function(b){var d=a.g;b=[+new Date-(h.c.F!==s?h.c.F:q),d(b.id),d(b.ba),d(b.ma),d(b.aa),d(b.link),d(b.content),b.type,b.wc].join("*");t.ra(b);a.e(this.$(),"Function")&&this.$()()},ra:function(a){a.length>e.P||(encodeURIComponent(r.join("!")+a).length>e.P&&(t.z(r.join("!")),r=[]),r.push(a))},
z:function(a){h.c.b.et=5;h.c.b.ep=a;h.c.b.p=l(f.A("autoEventTracking"));h.c.i();h.c.b.p=""},$:function(){return function(){r&&r.length&&(t.z(r.join("!")),r=[])}}};a.L(c.aet)&&""!==c.aet&&m.d("pv-b",function(){g.d(document,"click",t.ca());"ontouchend"in document&&g.d(window,"touchend",t.ca());g.d(window,"unload",t.$())});return t})();
(function(){var a=mt.event,b=mt.h,g=h.s,d=h.w,e=+new Date,m=[],f=v,l={xb:function(){return function(){h.c&&(h.c.X&&c.aet&&c.aet.length)&&(window.clearTimeout(f),f=window.setTimeout(function(){l.ib(b.W()+b.J())},150))}},ib:function(a){l.ra([+new Date-(h.c.F!==s?h.c.F:e),a].join("*"))},ra:function(a){if(encodeURIComponent(m.join("!")+a).length>g.P||3<m.length)l.z(m.join("!")),m=[];m.push(a)},z:function(a){h.c.b.et=6;h.c.b.vh=b.J();h.c.b.ep=a;h.c.i()},$:function(){return function(){m&&m.length&&(l.z(m.join("!")),
m=[])}}};mt.lang.L(c.aet)&&""!==c.aet&&d.d("pv-b",function(){a.d(window,"scroll",l.xb());a.d(window,"unload",l.$())});return l})();
(function(){var a=mt.f,b=h.s,g=h.load,d=h.Bb;h.w.d("pv-b",function(){var e=b.protocol+"//crs.baidu.com/";c.rec&&a.Ia(function(){for(var m=0,f=c.rp.length;m<f;m++){var l=c.rp[m][0],q=c.rp[m][1],r=a.va("hm_t_"+l);if(q&&!(2==q&&!r||r&&""!==r.innerHTML))r="",r=Math.round(Math.random()*b.N),r=4==q?e+"hl.js?"+["siteId="+c.id,"planId="+l,"rnd="+r].join("&"):e+"t.js?"+["siteId="+c.id,"planId="+l,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
r].join("&"),g(r)}})})})();
(function(){function a(){return function(){h.c.b.nv=0;h.c.b.st=4;h.c.b.et=3;h.c.b.ep=h.ta.Mb()+","+h.ta.Hb();h.c.i()}}function b(){clearTimeout(z);var a;p&&(a="visible"==document[p]);y&&(a=!document[y]);l="undefined"==typeof a?u:a;if((!f||!q)&&l&&r)k=u,n=+new Date;else if(f&&q&&(!l||!r))k=w,x+=+new Date-n;f=l;q=r;z=setTimeout(b,100)}function g(a){var p=document,b="";if(a in p)b=a;else for(var d=["webkit","ms","moz","o"],f=0;f<d.length;f++){var e=d[f]+a.charAt(0).toUpperCase()+a.slice(1);if(e in p){b=
e;break}}return b}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))r="focus"==a.type||"focusin"==a.type?u:w,b()}var e=mt.event,m=h.w,f=u,l=u,q=u,r=u,t=+new Date,n=t,x=0,k=u,p=g("visibilityState"),y=g("hidden"),z;b();(function(){var a=p.replace(/[vV]isibilityState/,"visibilitychange");e.d(document,a,b);e.d(window,"pageshow",b);e.d(window,"pagehide",b);"object"==typeof document.onfocusin?(e.d(document,"focusin",d),e.d(document,"focusout",d)):(e.d(window,"focus",d),
e.d(window,"blur",d))})();h.ta={Mb:function(){return+new Date-t},Hb:function(){return k?+new Date-n+x:x}};m.d("pv-b",function(){e.d(window,"unload",a())});m.d("duration-send",a());m.d("duration-done",function(){n=t=+new Date;x=0});return h.ta})();
(function(){var a=mt.lang,b=h.s,g=h.load,d={Zb:function(d){if((window._dxt===s||a.e(window._dxt,"Array"))&&"undefined"!==typeof h.c){var m=h.c.S();g([b.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(m)].join(""),d)}},vc:function(b){if(a.e(b,"String")||a.e(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.vb=d})();
(function(){function a(a,b,d,f){if(!(a===s||b===s||f===s)){if(""===a)return[b,d,f].join("*");a=String(a).split("!");for(var e,g=w,k=0;k<a.length;k++)if(e=a[k].split("*"),String(b)===e[0]){e[1]=d;e[2]=f;a[k]=e.join("*");g=u;break}g||a.push([b,d,f].join("*"));return a.join("!")}}function b(a){for(var f in a)if({}.hasOwnProperty.call(a,f)){var e=a[f];d.e(e,"Object")||d.e(e,"Array")?b(e):a[f]=String(e)}}var g=mt.url,d=mt.lang,e=mt.o,m=mt.h,f=h.s,l=h.w,q=h.vb,r=h.load,t=h.sa,n=h.Q,x=n.O,k={Z:[],la:0,Va:w,
C:{Ka:"",page:""},init:function(){k.j=0;n.init();l.d("pv-b",function(){k.wb();k.yb()});l.d("pv-d",function(){k.zb();k.C.page=""});l.d("stag-b",function(){h.c.b.api=k.j||k.la?k.j+"_"+k.la:"";h.c.b.ct=[decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),k.C.Ka,k.C.page].join("!")});l.d("stag-d",function(){h.c.b.api=0;k.j=0;k.la=0})},wb:function(){var a=window._hmt||[];if(!a||d.e(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var p=arguments[b];
d.e(p,"Array")&&(a.cmd[a.id].push(p),"_setAccount"===p[0]&&(1<p.length&&/^[0-9a-f]{32}$/.test(p[1]))&&(p=p[1],a.id=p,a.cmd[p]=a.cmd[p]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},yb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,f=0,e=b.length;f<e;f++){var g=b[f];d.test(g[0])?k.Z.push(g):k.Ga(g)}a.cmd[c.id]={push:k.Ga}},zb:function(){if(0<k.Z.length)for(var a=0,b=k.Z.length;a<b;a++)k.Ga(k.Z[a]);k.Z=
v},Ga:function(a){var b=a[0];if(k.hasOwnProperty(b)&&d.e(k[b],"Function"))k[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(k.j|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||u===a))k.j|=2,h.c.Ta=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){k.j|=4;h.c.b.sn=h.c.Ra();h.c.b.et=0;h.c.b.ep="";h.c.b.vl=m.W()+m.J();h.c.b.kb=0;h.c.Ba?(h.c.b.nv=0,h.c.b.st=4):h.c.Ba=u;var b=h.c.b.u,d=h.c.b.su;h.c.b.u=f.protocol+"//"+document.location.host+
a[1];k.Va||(h.c.b.su=document.location.href);h.c.b.p=x(n.A("pageview"));h.c.i();h.c.b.u=b;h.c.b.su=d;h.c.b.p="";h.c.F=+new Date;n.r("pageview")}},_trackEvent:function(a){2<a.length&&(k.j|=8,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=4,h.c.b.ep=d.g(a[1])+"*"+d.g(a[2])+(a[3]?"*"+d.g(a[3]):"")+(a[4]?"*"+d.g(a[4]):""),h.c.b.p=x(n.za()),h.c.i(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],f=a[4]||3;if(0<b&&6>b&&0<f&&4>f){k.la++;for(var e=(h.c.b.cv||"*").split("!"),g=e.length;g<b-1;g++)e.push("*");
e[b-1]=f+"*"+d.g(a[2])+"*"+d.g(a[3]);h.c.b.cv=e.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?t.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):t.mc("Hm_cv_"+c.id)}}},_setUserTag:function(b){if(!(3>b.length)){var f=d.g(b[1]);b=d.g(b[2]);if(f!==s&&b!==s){var e=decodeURIComponent(t.getData("Hm_ct_"+c.id)||""),e=a(e,f,1,b);t.setData("Hm_ct_"+c.id,encodeURIComponent(e),c.age)}}},_setVisitTag:function(b){if(!(3>b.length)){var f=d.g(b[1]);b=d.g(b[2]);if(f!==
s&&b!==s){var e=k.C.Ka,e=a(e,f,2,b);k.C.Ka=e}}},_setPageTag:function(b){if(!(3>b.length)){var f=d.g(b[1]);b=d.g(b[2]);if(f!==s&&b!==s){var e=k.C.page,e=a(e,f,3,b);k.C.page=e}}},_setReferrerOverride:function(a){1<a.length&&(h.c.b.su=a[1].charAt&&"/"===a[1].charAt(0)?f.protocol+"//"+window.location.host+a[1]:a[1],k.Va=u)},_trackOrder:function(a){a=a[1];d.e(a,"Object")&&(b(a),k.j|=16,h.c.b.nv=0,h.c.b.st=4,h.c.b.et=94,h.c.b.ep=e.stringify(a),h.c.b.p=x(n.za()),h.c.i(),h.c.b.p="")},_trackMobConv:function(a){if(a=
{webim:1,tel:2,map:3,sms:4,callback:5,share:6}[a[1]])k.j|=32,h.c.b.et=93,h.c.b.ep=a,h.c.i()},_setDataxId:function(a){a=a[1];q.Zb();q.vc(a)},_setUserId:function(a){a=a[1];if(a!==s&&(d.L(a)||d.Da(a))){var b=n.A("user").uid_;if(!(b&&b.value===d.g(String(a)))){var b=h.c.b.p,f=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+d.g(String(a));h.c.i();var e={};e.uid_=a;n.setProperty("user",e,u);h.c.b.p=b;h.c.b.ep=f}}},_clearUserId:function(a){1<a.length&&u===a[1]&&n.r("userId")},_setUserProperty:function(a){a=
a[1];d.e(a,"Object")&&n.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&u===a[1]&&n.r("user")},_setSessionProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("session",a)},_clearSessionProperty:function(a){1<a.length&&u===a[1]&&n.r("session")},_setPageviewProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&u===a[1]&&n.r("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];d.e(a,"Object")&&n.setProperty("autoEventTracking",
a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&u===a[1]&&n.r("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.Ua=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=a[1],w===a||u===a))h.c.X=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.i())):l.I("duration-send");l.I("duration-done")},_require:function(a){1<a.length&&(a=a[1],f.mb.test(g.V(a))&&r(a))},_providePlugin:function(a){if(1<
a.length){var b=window._hmt,e=a[1];a=a[2];if(d.K(f.Ya,e)&&d.e(a,"Function")&&(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]=a,b.B=b.B||[],a=b.B.slice(),e&&a.length&&a[0][1]===e))for(var g=0,k=a.length;g<k;g++){var l=a[g][2]||{};if(b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](l),b.B.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,e=a[1],g=a[2]||{};if(d.K(f.Ya,e))if(b.plugins=b.plugins||{},b.G=b.G||{},b.plugins[e]&&!b.G[e])b.G[e]=new b.plugins[e](g);else{b.B=b.B||
[];for(var g=0,l=b.B.length;g<l;g++)if(b.B[g][1]===e)return;b.B.push(a);k._require([v,f.jc+e+".js"])}}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];d.e(a,"Object")||(a={});a._iden=b;n.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=x(n.A("customEvent"));h.c.i();h.c.b.p="";n.r("customEvent")}}};k.init();h.nb=k;return h.nb})();
(function(){var a=h.w;c.spa!==s&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),a.d("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=u,this.b={},this.Ua=this.Ta=u,this.X=k.X,this.Oa=e.L(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.Ba=w,this.init())}var b=mt.url,g=mt.bb,d=mt.Ja,e=mt.lang,m=mt.cookie,f=mt.h,l=mt.sessionStorage,q=mt.o,r=mt.event,t=h.sa,n=h.Q,x=n.O,k=h.s,p=h.load,y=h.w;a.prototype={Y:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ha:function(a,
b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},fa:function(a){for(var d=0;d<c.dm.length;d++)if(-1<c.dm[d].indexOf("/")){if(this.ha(a,c.dm[d]))return u}else{var e=b.V(a);if(e&&this.Y(e,c.dm[d]))return u}return w},S:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.Y(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[/?#].*/,"");return a},da:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ha(document.location.href,d))return d.replace(/^[^/]+(\/.*)/,
"$1")+"/"}return"/"},Pb:function(){if(!document.referrer)return k.H-k.M>c.vdur?1:4;var a=w;this.fa(document.referrer)&&this.fa(document.location.href)?a=u:(a=b.V(document.referrer),a=this.Y(a||"",document.location.hostname));return a?k.H-k.M>c.vdur?1:4:3},tc:function(){var a,b,d,e,f;k.M=t.getData("Hm_lpvt_"+c.id)||0;13===k.M.length&&(k.M=Math.round(k.M/1E3));b=this.Pb();a=4!==b?1:0;if(d=t.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/
1E3));for(;2592E3<k.H-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(k.H);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=k.H,e="",f=1;t.setData("Hm_lvt_"+c.id,d,c.age);t.setData("Hm_lpvt_"+c.id,k.H);d=m.ec(this.S(),this.da());if(0===c.nv&&this.fa(document.location.href)&&(""===document.referrer||this.fa(document.referrer)))a=0,b=4;this.b.nv=a;this.b.st=b;this.b.cc=d;this.b.lt=e;this.b.lv=f},$a:function(){for(var a=[],b=this.b.et,d=+new Date,e=0,f=k.cb.length;e<f;e++){var g=k.cb[e],
l=this.b[g];"undefined"!==typeof l&&""!==l&&("tt"!==g||"tt"===g&&0===b)&&(("ct"!==g||"ct"===g&&0===b)&&("kb"!==g||"kb"===g&&3===b))&&a.push(g+"="+encodeURIComponent(l))}switch(b){case 0:this.b.rt&&a.push("rt="+encodeURIComponent(this.b.rt));break;case 5:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 6:a.push("_lpt="+this.F);a.push("_ct="+d);break;case 90:this.b.rt&&a.push("rt="+this.b.rt)}return a.join("&")},uc:function(){this.tc();this.b.si=c.id;this.b.sn=this.Ra();this.b.su=document.referrer;
this.b.ds=f.nc;this.b.cl=f.colorDepth+"-bit";this.b.ln=String(f.language).toLowerCase();this.b.ja=f.javaEnabled?1:0;this.b.ck=f.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.fl=d.Rb();this.b.v="1.2.68";this.b.cv=decodeURIComponent(t.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=f.W()+f.J();var a=document.location.href;this.b.cm=b.m(a,k.Wb)||"";this.b.cp=b.m(a,k.Xb)||b.m(a,k.zc)||"";this.b.cw=b.m(a,k.Vb)||b.m(a,k.Bc)||"";this.b.ci=b.m(a,k.Tb)||b.m(a,k.yc)||
"";this.b.cf=b.m(a,k.Yb)||b.m(a,k.Ac)||"";this.b.cu=b.m(a,k.Ub)||b.m(a,k.xc)||"";f.bc()&&(this.b.u=window.location.href)},init:function(){try{this.uc(),0===this.b.nv?this.sc():this.Qa(),h.c=this,this.pb(),this.ob(),y.I("pv-b"),this.qc()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));g.log(k.ia+"//"+k.Ha+"?"+b.join("&"))}},qc:function(){function a(){y.I("pv-d")}this.Ta?(this.Ba=
u,this.b.et=0,this.b.ep="",this.b.p=x(n.A("pageview")),this.b.vl=f.W()+f.J(),this.i(a),this.b.p=""):a();this.F=+new Date;n.r("pageview")},i:function(a){if(this.Ua){var b=this;b.b.rnd=Math.round(Math.random()*k.N);y.I("stag-b");var d=k.ia+"//"+k.Ha+"?"+b.$a();y.I("stag-d");b.lb(d);g.log(d,function(d){b.Za(d);e.e(a,"Function")&&a.call(b)})}},pb:function(){var a=document.location.hash.substring(1),d=RegExp(c.id),e=b.V(document.referrer)===k.eb?1:0,f=b.m(a,"jn"),g=/^heatlink$|^select$|^pageclick$/.test(f);
a&&(d.test(a)&&e&&g)&&(this.b.rnd=Math.round(Math.random()*k.N),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",k.protocol+"//"+c.js+f+".js?"+this.b.rnd),f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(a,f))},ob:function(){if(window.postMessage&&window.self!==window.parent){var a=this;r.d(window,"message",function(d){if(b.V(d.origin)===k.eb){d=d.data||{};var e=d.jn||"",f=/^customevent$/.test(e);
if(RegExp(c.id).test(d.sd||"")&&f)a.b.rnd=Math.round(Math.random()*k.N),p(k.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}},lb:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);l.set("Hm_unsent_"+c.id,q.stringify(b))},Za:function(a){var b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||
"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?l.set("Hm_unsent_"+c.id,q.stringify(b)):this.Qa()}},Qa:function(){l.remove("Hm_unsent_"+c.id)},sc:function(){var a=this,b;try{b=q.parse(l.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length)for(var e=function(b){g.log(k.ia+"//"+b,function(b){a.Za(b)})},f=0;f<b.length;f++)e(b[f])},Ra:function(){return Math.round(+new Date/
1E3)%65535}};return new a})();(function(){var a=mt.event,b=mt.lang,g=h.s;if(c.kbtrk&&"undefined"!==typeof h.c){h.c.b.kb=b.Da(h.c.b.kb)?h.c.b.kb:0;var d=function(){h.c.b.et=85;h.c.b.ep=h.c.b.kb;h.c.i()};a.d(document,"keyup",function(){h.c.b.kb++});a.d(window,"unload",function(){d()});setInterval(d,g.fc)}})();var C=h.s,D=h.load;c.pt&&D([C.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));
(function(){var a=mt.h,b=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&(c.med||(!a.Ca||7<a.Jb())&&c.cvcc)){var e,m,f,l,q=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},r=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},t=function(a,g){var k={};k.n=e;k.t="clk";k.v=a;if(g){var l=g.getAttribute("href"),m=g.getAttribute("onclick")?""+g.getAttribute("onclick"):v,n=g.getAttribute("id")||"";f.test(l)?(k.sn=
"mediate",k.snv=l):b.e(m,"String")&&f.test(m)&&(k.sn="wrap",k.snv=m);k.id=n}h.c.b.et=86;h.c.b.ep=d.stringify(k);h.c.i();for(k=+new Date;400>=+new Date-k;);};if(c.med)m="/zoosnet",e="swt",f=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,l={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g=0,k=b.length;g<k;g++)d=b[g],e=
d.getAttribute("onclick"),d=d.getAttribute("href"),(f.test(e)||f.test(d))&&a.push(b[g]);return a}};else if(c.cvcc){m="/other-comm";e="other";f=c.cvcc.q||s;var n=c.cvcc.id||s;l={click:function(){for(var a=[],b=q(document.getElementsByTagName("a")),b=[].concat.apply(b,q(document.getElementsByTagName("area"))),b=[].concat.apply(b,q(document.getElementsByTagName("img"))),d,e,g,k=0,l=b.length;k<l;k++)d=b[k],f!==s?(e=d.getAttribute("onclick"),g=d.getAttribute("href"),n?(d=d.getAttribute("id"),(f.test(e)||
f.test(g)||n.test(d))&&a.push(b[k])):(f.test(e)||f.test(g))&&a.push(b[k])):n!==s&&(d=d.getAttribute("id"),n.test(d)&&a.push(b[k]));return a}}}if("undefined"!==typeof l&&"undefined"!==typeof f){var x;m+=/\/$/.test(m)?"":"/";var k=function(a,d){if(x===d)return t(m+a,d),w;if(b.e(d,"Array")||b.e(d,"NodeList"))for(var e=0,f=d.length;e<f;e++)if(x===d[e])return t(m+a+"/"+(e+1),d[e]),w};g.d(document,"mousedown",function(a){a=a||window.event;x=a.target||a.srcElement;var d={};for(r(l,function(a,e){d[a]=b.e(e,
"Function")?e():document.getElementById(e)});x&&x!==document&&r(d,k)!==w;)x=x.parentNode})}}})();(function(){var a=mt.f,b=mt.lang,g=mt.event,d=mt.o;if("undefined"!==typeof h.c&&b.e(c.cvcf,"Array")&&0<c.cvcf.length){var e={hb:function(){for(var b=c.cvcf.length,d,l=0;l<b;l++)(d=a.va(decodeURIComponent(c.cvcf[l])))&&g.d(d,"click",e.ua())},ua:function(){return function(){h.c.b.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.c.b.ep=d.stringify(a);h.c.i()}}};a.Ia(function(){e.hb()})}})();
(function(){var a=mt.event,b=mt.o;if(c.med&&"undefined"!==typeof h.c){var g={n:"anti",sb:0,kb:0,clk:0},d=function(){h.c.b.et=86;h.c.b.ep=b.stringify(g);h.c.i()};a.d(document,"click",function(){g.clk++});a.d(document,"keyup",function(){g.kb=1});a.d(window,"scroll",function(){g.sb++});a.d(window,"load",function(){setTimeout(d,5E3)})}})();})();
